apiVersion: v1
kind: Namespace
metadata:
  name: cloudformation-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudformation-stack-operator
  namespace: cloudformation-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudformation-stack-operator
  template:
    metadata:
      labels:
        app: cloudformation-stack-operator
    spec:
      containers:
      - command:
        - /go/main
        - --capability
        - CAPABILITY_NAMED_IAM
        image: jagrati8672/capa:v1
        env:
        - name: http_proxy
          value: "http://172.20.129.49:3128"
        - name: https_proxy
          value: "http://172.20.129.49:3128"
        - name: no_proxy
          value: "localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,172.20.18.0/24,0.0.0.0,100.73.0.1"
        imagePullPolicy: IfNotPresent
        name: cloudformation-stack
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: cloudformation-operator
