apiVersion: v1
kind: Namespace
metadata:
  name: cloudformation-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudformation-stack-operator
  namespace: cloudformation-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudformation-stack-operator
  template:
    metadata:
      labels:
        app: cloudformation-stack-operator
    spec:
      containers:
      - command:
        - /go/main
        - --capability
        - CAPABILITY_NAMED_IAM
        image: jagrati8672/capa:v1
        imagePullPolicy: IfNotPresent
        name: cloudformation-stack
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: cloudformation-operator
